---
title: "DifferentialExpressionFb"
author: "A.DeMartin"
date: "2024-02-21"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

## load packages
```{r load packages, warning=FALSE, include=FALSE}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
```

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/Project/Angelina/HumanHeartCarTrans/data/Human_heart_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
```

## set color vectors 
```{r set color vector}
colclusterName <- c("#67001f", "#b2182b", "#d6604d", "#f4a582", "#dfc27d","#003c30","#01665e","#35978f","#c7eae5","#4d4d4d","#1a1a1a","#8c510a", "#355C7D") 
names(colclusterName) <- c("CM" ,"Fb1", "Tcell", "PerivFb/VSMC", "Fb2", "NC", "BEC3", "AdipoC", "LEC", "BEC1", "Mph2","BEC2", "Mph1")

coldiseaseCond <- c("#202547","#BE3144","#727077","#355C7D","#779d8d")
names(coldiseaseCond) <- unique(seuratM$diseaseCond)
```

## DE genes Fb1 vs Fb2
```{r DE genes Fb1 vs Fb2}
#DE genes
Idents(seuratM) <- seuratM$clusterName
seuratFb <- subset(seuratM, clusterName %in% c("Fb1", "Fb2"))
levels(seuratFb)
DEGenesFb <- FindAllMarkers(seuratFb, only.pos=T,logfc.threshold = 0.2) %>% 
  dplyr::filter(p_val_adj < 0.1) 
#save 
write.table(DEGenesFb, 
            file= "/Users/immbio/Desktop/Project/Angelina/HumanHeartCarTrans/analysis/DeGenesFb",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)
```

## GSEA Fb1 vs Fb2
```{r GSEA Fb1 vs Fb2, fig.height=10, fig.width=12}
##adjust table
DEGenesFbadj <- DEGenesFb %>% rownames_to_column(., var = "long") %>%
  mutate(gene=gsub("^.*\\.", "", long))  %>%
  mutate(EnsID=gsub("\\..*","", long))

##GSEA
DEGenesFb1 <- DEGenesFbadj %>% filter (cluster == "Fb1")
egoFb1 <- enrichGO(gene = unique(DEGenesFb1$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFb1 <- setReadable(egoFb1, OrgDb = org.Hs.eg.db)
dotplot(egoFb1, showCategory=30, title = "Fb1", font.size = 10)

DEGenesFb2 <- DEGenesFbadj %>% filter (cluster == "Fb2")
egoFb2 <- enrichGO(gene = unique(DEGenesFb2$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFb2 <- setReadable(egoFb2, OrgDb = org.Hs.eg.db)
dotplot(egoFb2, showCategory=30, title = "Fb2", font.size = 10)
```
## sel GSEA Fb1 vs Fb2
```{r sel GSEA Fb1 vs Fb2, fig.height=5, fig.width=12}
## select top pathways
selFb1 <- c("GO:0007178","GO:0030198", "GO:0043434", "GO:0071559", "GO:0030509")
egoFb1fil <- egoFb1%>% filter(egoFb1@result$ID %in% selFb1)
#make ggbarplot
p <- ggbarplot(egoFb1fil@result, x = "Description", y = "Count", color= "#b2182b", size = 3, sort.val = "asc", orientation = "horizontal", lab.vjust = 1)
p

## select top pathways
selFb2 <- c("GO:0045333", "GO:0042692","GO:0009260" ,"GO:0070670", "GO:0034341")
egoFb2fil <- egoFb2%>% filter(egoFb2@result$ID %in% selFb2)
#make ggbarplot
p <- ggbarplot(egoFb2fil@result, x = "Description", y = "Count", color= "#dfc27d", size = 3, sort.val = "asc", orientation = "horizontal", lab.vjust = 1)
p
```

## session info
```{r date and session info}
date()
sessionInfo()
```
