---
title: "FbHighres"
author: "A.DeMartin"
date: "2024-02-21"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages, warning=FALSE, include=FALSE}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
```

## load file
```{r load merged file, eval=FALSE, include=TRUE}
##load merged file 
fileNam <- "/Users/immbio/Desktop/Project/Angelina/HumanHeartCarTrans/data/Human_heart_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
table(seuratM$orig.ident)
```

##set color vectors 
```{r set color vector}
colclusterName <- c("#67001f", "#D53E4F", "#f4a582", "#FEE08B", "#003c30","#01665e","#66C2A5", "#3288BD","#BEAED4", "#c7eae5","#355C7D","#202547","#B45B5C","#8c510a")
names(colclusterName) <- c("CM","Fb","PerivFb","VSMC","Int","BEC1", "BEC2","LEC","NC","AdipoC","Mph","Mph2","Tcell","Tcell2")

coldiseaseCond <- c("#dfc27d","#BE3144","#202547","#355C7D","#779d8d")
names(coldiseaseCond) <- c("healthy", "explant", "visit1", "visit2", "visit3")
```

## subset Fb, PerivFb, VSMC
```{r subset Fb PerivFb VSMC, eval=FALSE, include=TRUE}
Idents(seuratM) <- seuratM$clusterName
seuratAllFb <- subset(seuratM, clusterName %in% c("Fb", "PerivFb", "VSMC"))
levels(seuratAllFb)
DimPlot(seuratAllFb, reduction = "umap", cols = colclusterName, pt.size = 2)
```

## rerun seurat
```{r rerun seuratAllFb, eval=FALSE, include=TRUE}
seuratAllFb <- NormalizeData (object = seuratAllFb)
seuratAllFb <- FindVariableFeatures(object = seuratAllFb)
seuratAllFb <- ScaleData(object = seuratAllFb, verbose = TRUE)
seuratAllFb <- RunPCA(object=seuratAllFb, npcs = 30, verbose = FALSE)
##seuratAllFb <- RunTSNE(object=seuratAllFb, reduction="pca", dims = 1:20)
seuratAllFb <- RunUMAP(object=seuratAllFb, reduction="pca", dims = 1:20)
seuratAllFb <- FindNeighbors(object = seuratAllFb, reduction = "pca", dims= 1:20)

res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratAllFb <- FindClusters(object = seuratAllFb, resolution = res[i], random.seed = 1234)
}

table(seuratAllFb$orig.ident)
table(seuratAllFb$RNA_snn_res.0.25)
```

```{r save merged seurat object, eval=FALSE, include=TRUE}
### save seurat object
saveRDS(seuratAllFb, file="/Users/immbio/Desktop/Project/Angelina/HumanHeartCarTrans/data/Human_heart_AllFb.rds")
```

##############################end pre-processing##############################

## load file AllFb
```{r load file AllFb}
fileNam <- "/Users/immbio/Desktop/Project/Angelina/HumanHeartCarTrans/data/Human_heart_AllFb.rds"
seuratAllFb <- readRDS(fileNam)
table(seuratAllFb$dataset)
table(seuratAllFb$RNA_snn_res.0.25)
table(seuratAllFb$orig.ident)
```

```{r assign cluter}
#### cluster_name_Fb
seuratAllFb$clusterNameAllFb <- "clusterNameAllFb"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "0" )] <- "Fb1"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "1" )] <- "PerivFb1"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "2" )] <- "Fb2"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "3" )] <- "Fb3"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "4" )] <- "VSMC"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "5" )] <- "Fb4"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "6" )] <- "PerivFb2"
seuratAllFb$clusterNameAllFb[which(seuratAllFb$RNA_snn_res.0.25 %in% "7" )] <- "PerivFb3"

table(seuratAllFb$clusterNameAllFb)
table(seuratAllFb$RNA_snn_res.0.25)

###order
Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
seuratAllFb$clusterNameAllFb <- factor(seuratAllFb$clusterNameAllFb, levels=c("Fb1", "Fb2", "Fb3", "Fb4", "PerivFb1", "PerivFb2", "PerivFb3", "VSMC"))
Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
table(seuratAllFb$clusterNameAllFb)
```

##set color vectors AllFb
```{r set color vector AllFb}
colAllFb <- c("#D53E4F","#f4a582","#ff7b7b","#8e0b00","#FEE08B","#42090D","#FF7B00","#FFF4DF")
names(colAllFb) <- c("Fb1","PerivFb1","Fb2","Fb3","VSMC","Fb4","PerivFb2", "PerivFb3")
```

## umaps
```{r umaps}
Idents(seuratAllFb) <- seuratAllFb$clusterName
DimPlot(seuratAllFb, reduction = "umap", pt.size = 0.5, cols = colclusterName, label = TRUE)

Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
DimPlot(seuratAllFb, reduction = "umap", pt.size = 0.5, cols = colAllFb, label = TRUE)
DimPlot(seuratAllFb, reduction = "umap", pt.size = 0.5, cols = colAllFb)  + theme(legend.position = "null")

Idents(seuratAllFb) <- seuratAllFb$diseaseCond
DimPlot(seuratAllFb, reduction = "umap", pt.size = 0.5, cols = coldiseaseCond)
DimPlot(seuratAllFb, reduction = "umap", pt.size = 0.5, cols = coldiseaseCond) + theme(legend.position = "null")
```

## calculate cluster marker genes
```{r cluster marker genes}
##cluster marker
Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
markerGenes <- FindAllMarkers(seuratAllFb, only.pos=T, logfc.threshold = 0.2) %>% 
  dplyr::filter(p_val_adj < 0.01)
```
## order datasets
```{r order, include=FALSE}
orddatasets <- c("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM","o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM","o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM","o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM","o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM","o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM","o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM","o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM","o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM","o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM",
"334131_10-10_20231108_Hu_nucseq_USZ_HTx001_RV","331571_3-5_20231012_Hu_nucseq_USZ_HTx001",
"334131_01-1_20231103_Hu_nucseq_USZ_HTx002_RV","331571_4-6_20231012_Hu_nucseq_USZ_HTx002",
"334131_04-4_20231106_Hu_nucseq_USZ_HTx003_RV","334131_02-2_20231103_Hu_nucseq_USZ_HTx003_LV",
"334131_03-3_20231103_Hu_nucseq_USZ_HTx004_RV","334131_05-5_20231106_Hu_nucseq_USZ_HTx004_LV", 
"334131_06-6_20231106_Hu_nucseq_USZ_HTx005_RV","334131_07-7_20231107_Hu_nucseq_USZ_HTx005_LV",
"334131_08-8_20231107_Hu_nucseq_USZ_HTx006_RV","334131_09-9_20231108_Hu_nucseq_USZ_HTx006_LV",
"340821_12-18_20240123_Hu_nucseq_USZ_HTx007_RV","340821_13-19_20240123_Hu_nucseq_USZ_HTx007_LV",
"336431_07-7_20231129_Hu_nucseq_USZ_HTx008_RV","336431_09-9_20231129_Hu_nucseq_USZ_HTx008_LV",
"347741_4-4_20240326_Hu_nucseq_USZ_HTx010_RV","347741_5-5_20240326_Hu_nucseq_USZ_HTx010_LV",
"353921_01-1_20240515_Hu_nucseq_USZ_HTx011_RV","353921_02-2_20240515_Hu_nucseq_USZ_HTx011_LV",
"353921_05-5_20240515_Hu_nucseq_USZ_HTx012_RV","353921_06-6_20240515_Hu_nucseq_USZ_HTx012_LV",
"353921_09-9_20240515_Hu_nucseq_USZ_HTx013_RV","353921_10-10_20240515_Hu_nucseq_USZ_HTx013_LV",
"353921_21-21_20240524_Hu_nucseq_USZ_HTx014_RV","353921_22-22_20240524_Hu_nucseq_USZ_HTx014_LV",
"353921_13-13_20240524_Hu_nucseq_USZ_HTx015_RV", "353921_17-17_20240524_Hu_nucseq_USZ_HTx015_LV",
"359861_02-2_20240715_Hu_nucseq_USZ_HTx016_RV","359861_01-1_20240715_Hu_nucseq_USZ_HTx016_LV",
"336431_08-8_20231129_Hu_nucseq_USZ_EMB001_V1","340831_1-1_20240118_Hu_nucseq_USZ_EMB001_V2","340821_03-9_20240123_Hu_nucseq_USZ_EMB001_V3",
"336431_13-13_20231129_Hu_nucseq_USZ_EMB002_V1","340831_2-2_20240118_Hu_nucseq_USZ_EMB002_V2","340821_04-10_20240123_Hu_nucseq_USZ_EMB002_V3",
"336431_14-14_20231129_Hu_nucseq_USZ_EMB003_V1","340831_3-3_20240118_Hu_nucseq_USZ_EMB003_V2","340821_05-11_20240123_Hu_nucseq_USZ_EMB003_V3",
"336431_15-15_20231129_Hu_nucseq_USZ_EMB004_V1","340831_4-4_20240118_Hu_nucseq_USZ_EMB004_V2","340821_06-12_20240123_Hu_nucseq_USZ_EMB004_V3",
"336431_10-10_20231129_Hu_nucseq_USZ_EMB005_V1","340831_5-5_20240118_Hu_nucseq_USZ_EMB005_V2","340821_07-13_20240123_Hu_nucseq_USZ_EMB005_V3",
"336431_11-11_20231129_Hu_nucseq_USZ_EMB006_V1","340831_6-6_20240118_Hu_nucseq_USZ_EMB006_V2","340821_08-14_20240123_Hu_nucseq_USZ_EMB006_V3",
"336431_12-12_20231129_Hu_nucseq_USZ_EMB007_V1","340821_01-7_20240118_Hu_nucseq_USZ_EMB007_V2","340821_09-15_20240123_Hu_nucseq_USZ_EMB007_V3",
"340821_11-17_20240123_Hu_nucseq_USZ_EMB008_V1","340821_02-8_20240118_Hu_nucseq_USZ_EMB008_V2","340821_10-16_20240123_Hu_nucseq_USZ_EMB008_V3",
"353921_11-11_20240515_Hu_nucseq_USZ_EMB010_V1_1","353921_12-12_20240515_Hu_nucseq_USZ_EMB010_V1_2","353921_08-8_20240515_Hu_nucseq_USZ_EMB010_V3", "353921_03-3_20240515_Hu_nucseq_USZ_EMB011_V1","353921_04-4_20240515_Hu_nucseq_USZ_EMB011_V2","353921_14-14_20240524_Hu_nucseq_USZ_EMB011_V3", "353921_07-7_20240515_Hu_nucseq_USZ_EMB012_V1","353921_15-15_20240524_Hu_nucseq_USZ_EMB012_V2","353921_16-16_20240524_Hu_nucseq_USZ_EMB012_V3", "353921_18-18_20240524_Hu_nucseq_USZ_EMB013_V1","353921_19-19_20240524_Hu_nucseq_USZ_EMB013_V2","353921_20-20_20240524_Hu_nucseq_USZ_EMB013_V3",
"353921_23-23_20240524_Hu_nucseq_USZ_EMB014_V1","353921_24-24_20240524_Hu_nucseq_USZ_EMB014_V2", "359861_03-3_20240715_Hu_nucseq_USZ_EMB014_V3",
"359861_04-4_20240715_Hu_nucseq_USZ_EMB015_V1","359861_05-5_20240715_Hu_nucseq_USZ_EMB015_V2","359861_06-6_20240715_Hu_nucseq_USZ_EMB015_V3",
"359861_07-7_20240715_Hu_nucseq_USZ_EMB016_V1","359861_08-8_20240715_Hu_nucseq_USZ_EMB016_V2","359861_18-10_20240730_Hu_nucseq_USZ_EMB016_V3")

ordpatient_diseasecond <- c("HH1_healthy","HH10_healthy","HH2_healthy","HH3_healthy","HH4_healthy","HH5_healthy","HH6_healthy","HH7_healthy","HH8_healthy","HH9_healthy","CarTransPat1_explant","CarTransPat2_explant","CarTransPat3_explant","CarTransPat4_explant","CarTransPat5_explant","CarTransPat6_explant","CarTransPat7_explant","CarTransPat8_explant","CarTransPat10_explant","CarTransPat11_explant","CarTransPat12_explant","CarTransPat13_explant","CarTransPat14_explant","CarTransPat15_explant", "CarTransPat16_explant",
"CarTransPat1_visit1","CarTransPat1_visit2","CarTransPat1_visit3","CarTransPat2_visit1","CarTransPat2_visit2","CarTransPat2_visit3","CarTransPat3_visit1","CarTransPat3_visit2","CarTransPat3_visit3","CarTransPat4_visit1","CarTransPat4_visit2","CarTransPat4_visit3","CarTransPat5_visit1","CarTransPat5_visit2","CarTransPat5_visit3","CarTransPat6_visit1","CarTransPat6_visit2","CarTransPat6_visit3","CarTransPat7_visit1","CarTransPat7_visit2","CarTransPat7_visit3","CarTransPat8_visit1","CarTransPat8_visit2","CarTransPat8_visit3","CarTransPat10_visit1","CarTransPat10_visit2","CarTransPat10_visit3","CarTransPat11_visit1","CarTransPat11_visit2","CarTransPat11_visit3","CarTransPat12_visit1","CarTransPat12_visit2","CarTransPat12_visit3","CarTransPat13_visit1","CarTransPat13_visit2","CarTransPat13_visit3","CarTransPat14_visit1","CarTransPat14_visit2", "CarTransPat14_visit3","CarTransPat15_visit1","CarTransPat15_visit2", "CarTransPat15_visit3","CarTransPat16_visit1","CarTransPat16_visit2", "CarTransPat16_visit3")

orddiseaseCond <- c("healthy", "explant", "visit1", "visit2" ,"visit3")
```

## abundance plots
```{r abundance dataset, fig.height=8, fig.width=10}
###dataset
datList <- NULL
for(con in unique(seuratAllFb$dataset)){
  seuratSub <- subset(seuratAllFb, dataset==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterNameAllFb)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(dataset=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

## plot abundance
ggbarplot(dat_all, x= "dataset", y= "percent", fill = "Var1", palette = colAllFb, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=orddatasets)
```
```{r abundance patient_diseaseCond, fig.height=8, fig.width=10}
###patient_diseaseCond
datList <- NULL
for(con in unique(seuratAllFb$patient_diseaseCond)){
  seuratSub <- subset(seuratAllFb, patient_diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterNameAllFb)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(patient_diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

## plot abundance
ggbarplot(dat_all, x= "patient_diseaseCond", y= "percent", fill = "Var1", palette = colAllFb, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=ordpatient_diseasecond)
```

```{r abundance diseaseCond, fig.height=8, fig.width=10}
###diseaseCond
datList <- NULL
for(con in unique(seuratAllFb$diseaseCond)){
  seuratSub <- subset(seuratAllFb, diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterNameAllFb)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

## plot abundance
ggbarplot(dat_all, x= "diseaseCond", y= "percent", fill = "Var1", palette = colAllFb, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=orddiseaseCond)
```
avg heatmaps
```{r heatmap top genes Fb1-4, fig.height=10, fig.width=8}
Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
levels(seuratAllFb)

seurat <- seuratAllFb

avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  selGenes <- selGenes$gene
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      celltype=colVec)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
  ordVec <- levels(seurat)
  ordVec <-c("Fb1", "Fb2", "Fb3", "Fb4", "PerivFb1", "PerivFb2", "PerivFb3", "VSMC")
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0,cluster_rows = cr, 
         cluster_cols = cc, color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

genesPlot <- data.frame(gene=c("ABCA6", "MEG3", "FKBP5", "ABCA8", "TSC22D3", "ABCA10", "LAMA2", "ZBTB16", "LAMB1", "USP53", "MEG3", "TNFAIP2", "MEG8", "PTGIR", "C7", "ABCA9", "LSP1", "TNXB", "C3", "ABCA10", "CCN2", "FN1", "CCDC80", "LTBP2", "COL1A1", "CEROX1","COL1A2", "MEG3", "VCAN", "SERPINE2", "FOS", "EGR1", "NR4A1", "FOSB", "BTG2", "ZFP36", "DUSP1", "CCN1", "FKBP5", "MIR23AHG"))

levels(seurat)
colVec <- colAllFb

# colVec <- c(colPal, colPal, colPal)
# colVec <- c("blue", "red")

avgHeatmap(seurat, selGenes = genesPlot, colVecIdent = colVec)
```

```{r heatmap top genes PerivFb1-3 VSMC, fig.height=10, fig.width=8}
Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
levels(seuratAllFb)

seurat <- seuratAllFb

avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  selGenes <- selGenes$gene
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      celltype=colVec)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
  ordVec <- levels(seurat)
  ordVec <-c("Fb1", "Fb2", "Fb3", "Fb4", "PerivFb1", "PerivFb2", "PerivFb3", "VSMC")
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0,cluster_rows = cr, 
         cluster_cols = cc, color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

genesPlot <- data.frame(gene=c("CD36", "CARMN", "RGS5", "ABCC9", "ITGA7", "DLC1", "NFASC", "PDGFRB", "AGAP2", "GJC1", "HIGD1B", "KLHL23", "DENND3", "CPM", "CCL2", "RGS16", "CXCL10", "CXCL8", "CXCL9", "GBP1", "ICAM1", "IRF1", "SOD2", "RELB", "MYH11", "TBX2", "MCAM", "GRIP2", "PPP1R12B", "ACTA2", "FLNA", "IRAG1"))

levels(seurat)
colVec <- colAllFb

# colVec <- c(colPal, colPal, colPal)
# colVec <- c("blue", "red")

avgHeatmap(seurat, selGenes = genesPlot, colVecIdent = colVec)
```
## calculate DE genes in Fb 1-4
```{r DE genes Fb 1-4}
## subset Fb1-4
table(seuratAllFb$clusterNameAllFb)
seuratFb1to4 <- subset(seuratAllFb, clusterNameAllFb %in% c("Fb1", "Fb2", "Fb3", "Fb4"))
table(seuratFb1to4$clusterNameAllFb)

Idents(seuratFb1to4) <- seuratFb1to4$clusterNameAllFb
levels(seuratFb1to4)
DEGenesFb1to4 <- FindAllMarkers(seuratFb1to4, only.pos=T, logfc.threshold = 0.2) %>% 
  dplyr::filter(p_val_adj < 0.01)
```
## GSEA Fb1-4
```{r GSEA Fb1, fig.height=10, fig.width=12}
##adjust table
DEGenesFb1to4adj <- DEGenesFb1to4 %>% 
  mutate(Gene=gene) %>%
  mutate(gene=gsub("^.*\\.", "", Gene))  %>%
  mutate(EnsID=gsub("\\..*","", Gene))

##GSEA Fb1
DEGenesFb1 <- DEGenesFb1to4adj %>% filter(cluster == "Fb1")
egoFb1 <- enrichGO(gene = unique(DEGenesFb1$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFb1 <- setReadable(egoFb1, OrgDb = org.Hs.eg.db)
dotplot(egoFb1, showCategory=30, title = "Fb1", font.size = 10)
```

## convert to sce 
```{r convert to sce}
##convert seurat object to sce object
sce <- as.SingleCellExperiment(seuratAllFb)
genes <- data.frame(geneID=rownames(sce)) %>% mutate(gene=gsub(".*\\.", "", geneID))
pal = colorRampPalette(c("#053061", "#2166ac", "#f7f7f7", "#f4a582", "#b2183c", "#85122d"))
```

```{r umap ECM organization}
ego1 <- dplyr::filter(egoFb1@result,egoFb1@result$Description=="extracellular matrix organization")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 2))
sceSub$sign2[which(sceSub$sign > 2)] <- 2
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

```{r GSEA Fb2, fig.height=10, fig.width=12}
##GSEA Fb2
DEGenesFb2 <- DEGenesFb1to4adj %>% filter(cluster == "Fb2")
egoFb2 <- enrichGO(gene = unique(DEGenesFb2$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFb2 <- setReadable(egoFb2, OrgDb = org.Hs.eg.db)
dotplot(egoFb2, showCategory=30, title = "Fb2", font.size = 10)
```

```{r umap muscle cell differentiation}
ego1 <- dplyr::filter(egoFb2@result,egoFb2@result$Description=="muscle cell differentiation")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.5))
sceSub$sign2[which(sceSub$sign > 0.5)] <- 0.5
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

```{r umap response to type II interferon}
ego1 <- dplyr::filter(egoFb2@result,egoFb2@result$Description=="response to type II interferon")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1))
sceSub$sign2[which(sceSub$sign > 1)] <- 1
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

```{r GSEA Fb3, fig.height=10, fig.width=12}
##GSEA Fb3
DEGenesFb3 <- DEGenesFb1to4adj %>% filter(cluster == "Fb3")
egoFb3 <- enrichGO(gene = unique(DEGenesFb3$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFb3 <- setReadable(egoFb3, OrgDb = org.Hs.eg.db)
dotplot(egoFb3, showCategory=30, title = "Fb3", font.size = 10)
```
```{r umap Wnt signaling pathway}
ego1 <- dplyr::filter(egoFb3@result,egoFb3@result$Description=="Wnt signaling pathway")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.5))
sceSub$sign2[which(sceSub$sign > 0.5)] <- 0.5
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

```{r umap transforming growth factor beta receptor signaling pathway}
ego1 <- dplyr::filter(egoFb3@result,egoFb3@result$Description=="transforming growth factor beta receptor signaling pathway")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.8))
sceSub$sign2[which(sceSub$sign > 0.8)] <- 0.8
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

```{r umap BMP signaling pathway}
ego1 <- dplyr::filter(egoFb3@result,egoFb3@result$Description=="BMP signaling pathway")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.8))
sceSub$sign2[which(sceSub$sign > 0.8)] <- 0.8
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

```{r GSEA Fb4, fig.height=10, fig.width=12}
##GSEA Fb4
DEGenesFb4 <- DEGenesFb1to4adj %>% filter(cluster == "Fb4")
egoFb4 <- enrichGO(gene = unique(DEGenesFb4$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFb4 <- setReadable(egoFb4, OrgDb = org.Hs.eg.db)
dotplot(egoFb4, showCategory=30, title = "Fb4", font.size = 10)
```


```{r umap response to steroid hormone}
ego1 <- dplyr::filter(egoFb4@result,egoFb4@result$Description=="response to steroid hormone")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
##check max and min values
##max(sceSub$sign)
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1))
sceSub$sign2[which(sceSub$sign > 1)] <- 1
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 0.5) + sc
```

## subset Fb4
```{r subset Fb4}
Idents(seuratAllFb) <- seuratAllFb$clusterNameAllFb
seuratFb2 <- subset(seuratAllFb, clusterNameAllFb %in% c("Fb2"))
levels(seuratFb2)
DimPlot(seuratFb2, reduction = "umap", cols = colAllFb, pt.size = 0.5)
```
```{r violin plots Fb2}
seuratFb2$diseaseCond <- factor(seuratFb2$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratFb2) <- seuratFb2$diseaseCond
levels(seuratFb2)
VlnPlot(object=seuratFb2, features = "ENSG00000172724.CCL19", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratFb2, features = "ENSG00000108691.CCL2", pt.size = 0, cols = coldiseaseCond)
VlnPlot(object=seuratFb2, features = "ENSG00000172156.CCL11", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratFb2, features = "ENSG00000125347.IRF1", pt.size = 0, cols = coldiseaseCond)
VlnPlot(object=seuratFb2, features = "ENSG00000115415.STAT1", pt.size = 0, cols = coldiseaseCond)

VlnPlot(object=seuratFb2, features = "ENSG00000169245.CXCL10", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratFb2, features = "ENSG00000163739.CXCL1", pt.size = 1, cols = coldiseaseCond)
```


## session info
```{r date and session info}
date()
sessionInfo()
```
