---
title: "GeneExprPatterns"
author: "A.DeMartin"
date: "2024-02-21"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages, warning=FALSE, include=FALSE}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
```

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/Project/Angelina/HumanHeartCarTrans/data/Human_heart_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
```

##set color vectors 
```{r set color vector}
colclusterName <- c("#67001f", "#D53E4F", "#f4a582", "#FEE08B", "#003c30","#01665e","#66C2A5", "#3288BD","#BEAED4", "#c7eae5","#355C7D","#202547","#B45B5C","#8c510a")
names(colclusterName) <- c("CM","Fb","PerivFb","VSMC","Int","BEC1", "BEC2","LEC","NC","AdipoC","Mph","Mph2","Tcell","Tcell2")

coldiseaseCond <- c("#dfc27d","#BE3144","#202547","#355C7D","#779d8d")
names(coldiseaseCond) <- c("healthy", "explant", "visit1", "visit2", "visit3")
```

## plot features
```{r feature plot}
FeaturePlot(seuratM, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = c("lightgrey", "#BE3144"), raster = FALSE)
FeaturePlot(seuratM, features = "ENSG00000159674.SPON2", pt.size = 1, cols = c("lightgrey", "#BE3144"), raster = FALSE)
FeaturePlot(seuratM, features = "ENSG00000065320.NTN1", pt.size = 1, cols = c("lightgrey", "#BE3144"), raster = FALSE)
FeaturePlot(seuratM, features = "ENSG00000164136.IL15", pt.size = 1, cols = c("lightgrey", "#BE3144"), raster = FALSE)
FeaturePlot(seuratM, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = c("lightgrey", "#BE3144"), raster = FALSE)

Idents(seuratM) <- seuratM$clusterName
VlnPlot(object=seuratM, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000159674.SPON2", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000065320.NTN1", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000164136.IL15", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = colclusterName)

seuratM$diseaseCond <- factor(seuratM$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratM) <- seuratM$diseaseCond
VlnPlot(object=seuratM, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratM, features = "ENSG00000159674.SPON2", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000065320.NTN1", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000164136.IL15", pt.size = 1, cols = colclusterName)
VlnPlot(object=seuratM, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = colclusterName)
```

```{r feature plot PerivFb}
## subset PerivFb
seuratPerivFb <- subset(seuratM, clusterName %in% c("PerivFb"))
Idents(seuratPerivFb) <- seuratPerivFb$clusterName
DimPlot(seuratPerivFb, reduction = "umap", cols = colclusterName)

#make violin plot
seuratPerivFb$diseaseCond <- factor(seuratPerivFb$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratPerivFb) <- seuratPerivFb$diseaseCond
VlnPlot(object=seuratPerivFb, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratPerivFb, features = "ENSG00000159674.SPON2", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratPerivFb, features = "ENSG00000065320.NTN1", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratPerivFb, features = "ENSG00000164136.IL15", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratPerivFb, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = coldiseaseCond)
```

```{r feature plot Fb}
## subset Fb
seuratFb <- subset(seuratM, clusterName %in% c("Fb"))
Idents(seuratFb) <- seuratFb$clusterName
DimPlot(seuratFb, reduction = "umap", cols = colclusterName)

#make violin plot
seuratFb$diseaseCond <- factor(seuratFb$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratFb) <- seuratFb$diseaseCond
VlnPlot(object=seuratFb, features = "ENSG00000197614.MFAP5", pt.size = 0, cols = coldiseaseCond)
VlnPlot(object=seuratFb, features = "ENSG00000159674.SPON2", pt.size = 0, cols = coldiseaseCond)
VlnPlot(object=seuratFb, features = "ENSG00000065320.NTN1", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratFb, features = "ENSG00000164136.IL15", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratFb, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = coldiseaseCond)
```

```{r feature plot CM}
## subset CM
seuratCM <- subset(seuratM, clusterName %in% c("CM"))
Idents(seuratCM) <- seuratCM$clusterName
DimPlot(seuratCM, reduction = "umap", cols = colclusterName)

#make violin plot
seuratCM$diseaseCond <- factor(seuratCM$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratCM) <- seuratCM$diseaseCond
VlnPlot(object=seuratCM, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratCM, features = "ENSG00000159674.SPON2", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratCM, features = "ENSG00000065320.NTN1", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratCM, features = "ENSG00000164136.IL15", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratCM, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = coldiseaseCond)
```

```{r feature plot BEC}
## subset BEC
seuratBEC <- subset(seuratM, clusterName %in% c("BEC1", "BEC2"))
Idents(seuratBEC) <- seuratBEC$clusterName
DimPlot(seuratBEC, reduction = "umap", cols = colclusterName)

#make violin plot
seuratBEC$diseaseCond <- factor(seuratBEC$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratBEC) <- seuratBEC$diseaseCond
VlnPlot(object=seuratBEC, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratBEC, features = "ENSG00000159674.SPON2", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratBEC, features = "ENSG00000065320.NTN1", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratBEC, features = "ENSG00000164136.IL15", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratBEC, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = coldiseaseCond)
```

```{r feature plot Mph}
## subset Mph
seuratMph <- subset(seuratM, clusterName %in% c("Mph", "Mph2"))
Idents(seuratMph) <- seuratMph$clusterName
DimPlot(seuratMph, reduction = "umap", cols = colclusterName, label = TRUE)

#make violin plot
seuratMph$diseaseCond <- factor(seuratMph$diseaseCond, levels=c("healthy", "explant", "visit1", "visit2", "visit3"))
Idents(seuratMph) <- seuratMph$diseaseCond
VlnPlot(object=seuratMph, features = "ENSG00000197614.MFAP5", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratMph, features = "ENSG00000159674.SPON2", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratMph, features = "ENSG00000065320.NTN1", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratMph, features = "ENSG00000164136.IL15", pt.size = 1, cols = coldiseaseCond)
VlnPlot(object=seuratMph, features = "ENSG00000172638.EFEMP2", pt.size = 1, cols = coldiseaseCond)
```
### dotplot 
```{r dotplot, fig.height=5, fig.width=20}
genes <- data.frame(gene=rownames(seuratM)) %>% 
  mutate(geneID=gsub("^.*\\.", "", gene))

selGenes <- data.frame(geneID=c("NTN1","IL15","EFEMP2", "MFAP5")) %>% left_join(., genes, by="geneID")

DotPlot(seuratM, features = selGenes, group.by= "clusterName_diseaseCond") + RotatedAxis() + scale_color_viridis(option="D") + coord_flip()
```
## session info
```{r date and session info}
date()
sessionInfo()
```
